# Site settings
title: "Sebastien Guilet Resume"
description: "sbeou's resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Sebastien Guilet"
resume_title:                   "Grafik and Web Desing / Front-End"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "design@walf.com.br"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "71 9 8511-9978"
resume_contact_address:         "Pituba, Salvador - Ba, Brazil"

resume_header_contact_info:     "Pituba, Salvador - Ba, Brazil • 71 9 8511-9978 • design@walf.com.br"
display_header_contact_info:    "false"

resume_header_intro: "<p>As a grafic and web designer / front-end, my approach embraces diversify while using the latest multimedia techniques for a unique result.</p>
<p>Born in France, I'm living in Brasil since 2013, speak french, fluent Portuguese and intermediate English</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
# resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/sbeou"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/sebatienguilet/"
  resume_instagram_url:         "https://www.instagram.com/webdesignalafrancaise/"
  resume_website_url:           "https://webdesignalafrancaise.com.br"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
