# Site settings
title: "Sebastien Guilet Resume"
description: "sbeou's resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Sebastien Guilet"
resume_title:                   "Designer and Front-end Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "sbeou13@gmail.comr"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+55 71 9 8511-9978"
resume_contact_address:         "Pituba, Salvador - Ba, Brazil"

resume_header_contact_info:     "Pituba, Salvador - Ba, Brazil • +55 71 9 8511-9978 • sbeou13@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>UX design and front-end developer, my approach embraces diversity while using the latest multimedia techniques for a unique result.</p><p>I draw my inspiration from the latest trends while bringing my personal touch.</P><p>I create websites from briefing to publication.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/sbeou"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/sebastienguilet/"
  resume_instagram_url:         "https://www.instagram.com/webdesignalafrancaise/"
  resume_website_url:           "https://french.dev.br"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
